/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectooperativosbmwbaladiinvernon;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.concurrent.Semaphore;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kathe
 */
public class Vista extends javax.swing.JFrame {

    //Mira aquí
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        
        initComponents();
        MainjPanel.setVisible(true);
        jLabel1.setVisible(false);
        DayNumberjTextField.setVisible(false);
        AcceptDayNumberjButton.setVisible(false);
        AppjPanel.setVisible(false);
        WheelMakerjTextField.setEditable(false);
        WheelQuantityjTextField.setEditable(false);
        WindshieldMakerjTextField.setEditable(false);
        WindshieldQuantityjTextField.setEditable(false);
        EngineMakerjTextField.setEditable(false);
        EngineQuantityjTextField.setEditable(false);
        CarMakerjTextField.setEditable(false);
        CarQuantityjTextField.setEditable(false);
        BossjTextField.setEditable(false);
        ManagerjTextField.setEditable(false);
        RemainingDaysjTextField.setEditable(false);
        /*
            WheelMakerjTextField.setText(String.valueOf(productoresRuedasActuales));
            WindshieldMakerjTextField.setText(String.valueOf(productoresParabirsasActuales));
            EngineMakerjTextField.setText(String.valueOf(productoresMotoresActuales));
            CarMakerjTextField.setText(String.valueOf(ensambladoresActuales));
            WheelQuantityjTextField.setText(String.valueOf(contadorRuedasProducidas));
            WindshieldQuantityjTextField.setText(String.valueOf(contadorParabrisasProducidos));
            EngineQuantityjTextField.setText(String.valueOf(contadorMotoresProducidos));
        */
        DayNumberjTextField.addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent event)
           {
              char character = event.getKeyChar();

              // Verifica si la tecla pulsada por el usuario no es un digito
              if(((character < '0') ||
                 (character > '9')) &&
                 (character != '\b'))  // el backspace
              {
                 event.consume();  // ignorar el teclado
              }
           }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainjPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DayNumberjTextField = new javax.swing.JTextField();
        AcceptDayNumberjButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        YesDefaultDaysjButton = new javax.swing.JButton();
        NoDefaultDaysjButton = new javax.swing.JButton();
        AppjPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        WheelQuantityjTextField = new javax.swing.JTextField();
        AddWheelMakerjButton = new javax.swing.JButton();
        DeleteWheelMakerjButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        DeleteWindshieldMakerjButton = new javax.swing.JButton();
        WindshieldMakerjTextField = new javax.swing.JTextField();
        AddWindshieldMakerjButton = new javax.swing.JButton();
        WindshieldQuantityjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EngineQuantityjTextField = new javax.swing.JTextField();
        AddEngineMakerjButton = new javax.swing.JButton();
        EngineMakerjTextField = new javax.swing.JTextField();
        DeleteEngineMakerjButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DeleteCarMakerjButton = new javax.swing.JButton();
        CarMakerjTextField = new javax.swing.JTextField();
        AddCarMakerjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CarQuantityjTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BossjTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ManagerjTextField = new javax.swing.JTextField();
        RemainingDaysjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        WheelMakerjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainjPanel.setBackground(new java.awt.Color(160, 246, 210));
        MainjPanel.setMaximumSize(new java.awt.Dimension(600, 650));
        MainjPanel.setMinimumSize(new java.awt.Dimension(600, 650));
        MainjPanel.setPreferredSize(new java.awt.Dimension(600, 650));

        jLabel1.setBackground(new java.awt.Color(160, 246, 210));
        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese la cantidad de días de trabajo");

        DayNumberjTextField.setBackground(new java.awt.Color(3, 65, 77));
        DayNumberjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        DayNumberjTextField.setForeground(new java.awt.Color(255, 255, 255));
        DayNumberjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DayNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayNumberjTextFieldActionPerformed(evt);
            }
        });

        AcceptDayNumberjButton.setBackground(new java.awt.Color(114, 223, 208));
        AcceptDayNumberjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        AcceptDayNumberjButton.setText("Aceptar");
        AcceptDayNumberjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        AcceptDayNumberjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptDayNumberjButtonActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(160, 246, 210));
        jLabel13.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel13.setText("¿Deseas utilizar la cantidad de días predeterminada?");

        YesDefaultDaysjButton.setBackground(new java.awt.Color(114, 223, 208));
        YesDefaultDaysjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        YesDefaultDaysjButton.setText("Si");
        YesDefaultDaysjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        YesDefaultDaysjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesDefaultDaysjButtonActionPerformed(evt);
            }
        });

        NoDefaultDaysjButton.setBackground(new java.awt.Color(114, 223, 208));
        NoDefaultDaysjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        NoDefaultDaysjButton.setText("No");
        NoDefaultDaysjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        NoDefaultDaysjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoDefaultDaysjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainjPanelLayout = new javax.swing.GroupLayout(MainjPanel);
        MainjPanel.setLayout(MainjPanelLayout);
        MainjPanelLayout.setHorizontalGroup(
            MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainjPanelLayout.createSequentialGroup()
                .addGroup(MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainjPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel13))
                    .addGroup(MainjPanelLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(YesDefaultDaysjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(NoDefaultDaysjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainjPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainjPanelLayout.createSequentialGroup()
                                .addComponent(DayNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AcceptDayNumberjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        MainjPanelLayout.setVerticalGroup(
            MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainjPanelLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesDefaultDaysjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(NoDefaultDaysjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AcceptDayNumberjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DayNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        AppjPanel.setBackground(new java.awt.Color(160, 246, 210));
        AppjPanel.setMaximumSize(new java.awt.Dimension(600, 650));
        AppjPanel.setMinimumSize(new java.awt.Dimension(600, 650));
        AppjPanel.setPreferredSize(new java.awt.Dimension(600, 650));
        AppjPanel.setRequestFocusEnabled(false);

        jLabel2.setBackground(new java.awt.Color(160, 246, 210));
        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel2.setText("Cantidad de Cauchos");

        jLabel3.setBackground(new java.awt.Color(160, 246, 210));
        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Productores de Cauchos");

        WheelQuantityjTextField.setBackground(new java.awt.Color(3, 65, 77));
        WheelQuantityjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        WheelQuantityjTextField.setForeground(new java.awt.Color(255, 255, 255));
        WheelQuantityjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WheelQuantityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelQuantityjTextFieldActionPerformed(evt);
            }
        });

        AddWheelMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        AddWheelMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddWheelMakerjButton.setText("+");
        AddWheelMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        DeleteWheelMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        DeleteWheelMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        DeleteWheelMakerjButton.setText("-");
        DeleteWheelMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        DeleteWheelMakerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteWheelMakerjButtonActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(160, 246, 210));
        jLabel4.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("Productores de Parabrisas");

        DeleteWindshieldMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        DeleteWindshieldMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        DeleteWindshieldMakerjButton.setText("-");
        DeleteWindshieldMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        WindshieldMakerjTextField.setBackground(new java.awt.Color(3, 65, 77));
        WindshieldMakerjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        WindshieldMakerjTextField.setForeground(new java.awt.Color(255, 255, 255));
        WindshieldMakerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WindshieldMakerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindshieldMakerjTextFieldActionPerformed(evt);
            }
        });

        AddWindshieldMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        AddWindshieldMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddWindshieldMakerjButton.setText("+");
        AddWindshieldMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        WindshieldQuantityjTextField.setBackground(new java.awt.Color(3, 65, 77));
        WindshieldQuantityjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        WindshieldQuantityjTextField.setForeground(new java.awt.Color(255, 255, 255));
        WindshieldQuantityjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WindshieldQuantityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WindshieldQuantityjTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(160, 246, 210));
        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("Cantidad de Parabrisas");

        jLabel6.setBackground(new java.awt.Color(160, 246, 210));
        jLabel6.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel6.setText("Productores de Motores");

        jLabel7.setBackground(new java.awt.Color(160, 246, 210));
        jLabel7.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel7.setText("Cantidad de Motores");

        EngineQuantityjTextField.setBackground(new java.awt.Color(3, 65, 77));
        EngineQuantityjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        EngineQuantityjTextField.setForeground(new java.awt.Color(255, 255, 255));
        EngineQuantityjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineQuantityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineQuantityjTextFieldActionPerformed(evt);
            }
        });

        AddEngineMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        AddEngineMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddEngineMakerjButton.setText("+");
        AddEngineMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        EngineMakerjTextField.setBackground(new java.awt.Color(3, 65, 77));
        EngineMakerjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        EngineMakerjTextField.setForeground(new java.awt.Color(255, 255, 255));
        EngineMakerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EngineMakerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineMakerjTextFieldActionPerformed(evt);
            }
        });

        DeleteEngineMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        DeleteEngineMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        DeleteEngineMakerjButton.setText("-");
        DeleteEngineMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        jLabel8.setBackground(new java.awt.Color(160, 246, 210));
        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ensambladores");

        DeleteCarMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        DeleteCarMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        DeleteCarMakerjButton.setText("-");
        DeleteCarMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        CarMakerjTextField.setBackground(new java.awt.Color(3, 65, 77));
        CarMakerjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        CarMakerjTextField.setForeground(new java.awt.Color(255, 255, 255));
        CarMakerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarMakerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarMakerjTextFieldActionPerformed(evt);
            }
        });

        AddCarMakerjButton.setBackground(new java.awt.Color(114, 223, 208));
        AddCarMakerjButton.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        AddCarMakerjButton.setText("+");
        AddCarMakerjButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));

        jLabel9.setBackground(new java.awt.Color(160, 246, 210));
        jLabel9.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel9.setText("Cantidad de Carros");

        CarQuantityjTextField.setBackground(new java.awt.Color(3, 65, 77));
        CarQuantityjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        CarQuantityjTextField.setForeground(new java.awt.Color(255, 255, 255));
        CarQuantityjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CarQuantityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarQuantityjTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(160, 246, 210));
        jLabel10.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("El jefe está:");

        BossjTextField.setBackground(new java.awt.Color(3, 65, 77));
        BossjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        BossjTextField.setForeground(new java.awt.Color(255, 255, 255));
        BossjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BossjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BossjTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(160, 246, 210));
        jLabel11.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel11.setText("El gerente está:");

        ManagerjTextField.setBackground(new java.awt.Color(3, 65, 77));
        ManagerjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        ManagerjTextField.setForeground(new java.awt.Color(255, 255, 255));
        ManagerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ManagerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagerjTextFieldActionPerformed(evt);
            }
        });

        RemainingDaysjTextField.setBackground(new java.awt.Color(3, 65, 77));
        RemainingDaysjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        RemainingDaysjTextField.setForeground(new java.awt.Color(255, 255, 255));
        RemainingDaysjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RemainingDaysjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemainingDaysjTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(160, 246, 210));
        jLabel12.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Días restantes");

        WheelMakerjTextField.setBackground(new java.awt.Color(3, 65, 77));
        WheelMakerjTextField.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 16)); // NOI18N
        WheelMakerjTextField.setForeground(new java.awt.Color(255, 255, 255));
        WheelMakerjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        WheelMakerjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WheelMakerjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AppjPanelLayout = new javax.swing.GroupLayout(AppjPanel);
        AppjPanel.setLayout(AppjPanelLayout);
        AppjPanelLayout.setHorizontalGroup(
            AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AppjPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(AppjPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AppjPanelLayout.createSequentialGroup()
                                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(AppjPanelLayout.createSequentialGroup()
                                                .addComponent(DeleteEngineMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EngineMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddEngineMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(AppjPanelLayout.createSequentialGroup()
                                                .addComponent(DeleteCarMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CarMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AddCarMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(92, 92, 92)
                                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppjPanelLayout.createSequentialGroup()
                                                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(WindshieldQuantityjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EngineQuantityjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(CarQuantityjTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(66, 66, 66))))
                                    .addGroup(AppjPanelLayout.createSequentialGroup()
                                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BossjTextField)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ManagerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RemainingDaysjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 50, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AppjPanelLayout.createSequentialGroup()
                                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AppjPanelLayout.createSequentialGroup()
                                        .addComponent(DeleteWindshieldMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WindshieldMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddWindshieldMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AppjPanelLayout.createSequentialGroup()
                                        .addComponent(DeleteWheelMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(WheelMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AddWheelMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WheelQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        AppjPanelLayout.setVerticalGroup(
            AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WheelQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddWheelMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteWheelMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WheelMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WindshieldMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WindshieldQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddWindshieldMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteWindshieldMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EngineMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddEngineMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteEngineMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EngineQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CarMakerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCarMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteCarMakerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CarQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AppjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BossjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManagerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AppjPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemainingDaysjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AppjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MainjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DayNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayNumberjTextFieldActionPerformed

    private void WheelQuantityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelQuantityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WheelQuantityjTextFieldActionPerformed

    private void WindshieldMakerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindshieldMakerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WindshieldMakerjTextFieldActionPerformed

    private void WindshieldQuantityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WindshieldQuantityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WindshieldQuantityjTextFieldActionPerformed

    private void EngineQuantityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineQuantityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineQuantityjTextFieldActionPerformed

    private void EngineMakerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineMakerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EngineMakerjTextFieldActionPerformed

    private void CarMakerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarMakerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarMakerjTextFieldActionPerformed

    private void CarQuantityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarQuantityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarQuantityjTextFieldActionPerformed

    private void BossjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BossjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BossjTextFieldActionPerformed

    private void ManagerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagerjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManagerjTextFieldActionPerformed

    private void RemainingDaysjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemainingDaysjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemainingDaysjTextFieldActionPerformed

    private void AcceptDayNumberjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptDayNumberjButtonActionPerformed
        // TODO add your handling code here:
        
        
        if(DayNumberjTextField.getText().equals("")){
        
            JOptionPane.showMessageDialog(null, "Debes llenar el campo para poder comenzar");
        }
        else{
        
            MainjPanel.setVisible(false);
            AppjPanel.setVisible(true);
        }
        
    }//GEN-LAST:event_AcceptDayNumberjButtonActionPerformed

    private void WheelMakerjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WheelMakerjTextFieldActionPerformed

    }//GEN-LAST:event_WheelMakerjTextFieldActionPerformed

    private void YesDefaultDaysjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesDefaultDaysjButtonActionPerformed
        // TODO add your handling code here:
        MainjPanel.setVisible(false);
        AppjPanel.setVisible(true);
        
    }//GEN-LAST:event_YesDefaultDaysjButtonActionPerformed

    private void NoDefaultDaysjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoDefaultDaysjButtonActionPerformed
        // TODO add your handling code here:
        jLabel1.setVisible(true);
        DayNumberjTextField.setVisible(true);
        AcceptDayNumberjButton.setVisible(true);
        jLabel13.setVisible(false);
        YesDefaultDaysjButton.setVisible(false);
        NoDefaultDaysjButton.setVisible(false);
        
    }//GEN-LAST:event_NoDefaultDaysjButtonActionPerformed

    private void DeleteWheelMakerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteWheelMakerjButtonActionPerformed
    }//GEN-LAST:event_DeleteWheelMakerjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Vista().setVisible(true);
            }
        });
        
        
    }
    
    
    
    
    public void contratarEnsamblador(int cantidadTrabajadores, Ensambladores[] ensambla, 
            Semaphore semR, String nombre,Semaphore semER, Semaphore semM,
            Semaphore semEM, Semaphore semP, Semaphore semEP, Semaphore semRG, 
            Semaphore semPG, Semaphore semMG, Semaphore semGE, int contadorCarrosProducidos, 
            boolean[] almacenRuedas, boolean[] almacenParabrisas, boolean[] almacenMotores,
            int contadorRuedasConsumidas, int contadorParabrisasConsumidos, int contadorMotoresConsumidos){
            ensambla[cantidadTrabajadores] = new Ensambladores(semR, nombre, semER, 
                semM, semEM, semP, semEP, semRG, semPG, semMG, semGE, 
                contadorCarrosProducidos, almacenRuedas, almacenParabrisas, 
                almacenMotores, contadorRuedasConsumidas, contadorParabrisasConsumidos, 
                contadorMotoresConsumidos);
            ensambla[cantidadTrabajadores].start();
            cantidadTrabajadores++;
    }
    
    public void contratarProductor(int cantidadTrabajadores, Productor[] prod, 
            Semaphore sem, String nombre, String tipoDeProducto,Semaphore semE, 
            int diasDeProduccion, int duracionDelDia, Semaphore semG, 
            boolean[] almacen, int contadorProducidos ){
            
                prod[cantidadTrabajadores] = new Productor(sem, nombre, tipoDeProducto, 
                semE, diasDeProduccion, duracionDelDia, semG, almacen, contadorProducidos);
                prod[cantidadTrabajadores].start();
                cantidadTrabajadores++;
    }
    
    public void despedir(int cantidadTrabajadores, Productor[] prod){
        prod[cantidadTrabajadores].setContratado(false);
        cantidadTrabajadores--;
    }
    public void despedir(int cantidadTrabajadores, Ensambladores[] ensambla){
        ensambla[cantidadTrabajadores].setContratado(false);
        cantidadTrabajadores--;
    }
    
    /*public void constante(){
        WheelMakerjTextField.setText(String.valueOf(productoresRuedasActuales));
        WindshieldMakerjTextField.setText(String.valueOf(productoresParabirsasActuales));
        EngineMakerjTextField.setText(String.valueOf(productoresMotoresActuales));
        CarMakerjTextField.setText(String.valueOf(ensambladoresActuales));
        WheelQuantityjTextField.setText(String.valueOf(contadorRuedasProducidas));
        WindshieldQuantityjTextField.setText(String.valueOf(contadorParabrisasProducidos));
        EngineQuantityjTextField.setText(String.valueOf(contadorMotoresProducidos));
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptDayNumberjButton;
    private javax.swing.JButton AddCarMakerjButton;
    private javax.swing.JButton AddEngineMakerjButton;
    private javax.swing.JButton AddWheelMakerjButton;
    private javax.swing.JButton AddWindshieldMakerjButton;
    private javax.swing.JPanel AppjPanel;
    private javax.swing.JTextField BossjTextField;
    public javax.swing.JTextField CarMakerjTextField;
    public javax.swing.JTextField CarQuantityjTextField;
    private javax.swing.JTextField DayNumberjTextField;
    private javax.swing.JButton DeleteCarMakerjButton;
    private javax.swing.JButton DeleteEngineMakerjButton;
    private javax.swing.JButton DeleteWheelMakerjButton;
    private javax.swing.JButton DeleteWindshieldMakerjButton;
    public javax.swing.JTextField EngineMakerjTextField;
    public javax.swing.JTextField EngineQuantityjTextField;
    private javax.swing.JPanel MainjPanel;
    public javax.swing.JTextField ManagerjTextField;
    private javax.swing.JButton NoDefaultDaysjButton;
    public javax.swing.JTextField RemainingDaysjTextField;
    public javax.swing.JTextField WheelMakerjTextField;
    public javax.swing.JTextField WheelQuantityjTextField;
    public javax.swing.JTextField WindshieldMakerjTextField;
    public javax.swing.JTextField WindshieldQuantityjTextField;
    private javax.swing.JButton YesDefaultDaysjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
